name: Create Theme Zip

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  find-changed-directories:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed theme
        id: changed-themes
        uses: tj-actions/changed-files@v35
        with:
          dir_names: true
          dir_names_max_depth: 2
          files_ignore: .github
      - name: Create zip for changed theme
        run: |
          for theme in ${{ steps.changed-themes.outputs.all_changed_files }}; do
            echo "$theme was changed"
            zip -r -X $theme.zip $theme
          done

      # - uses: vimtor/action-zip@v1
      #   with:
      #     files: dist/ manifest.json
      #     dest: theme-name.zip
      # - uses: actions/upload-artifact@v1
      # with:
      #   name: theme-name
      #   path: ${{ github.workspace }}/theme-name.zip
