name: Create Theme Zip

on:
  pull_request_target: # When a PR is opened
    types: [opened]
  workflow_dispatch:
jobs:
  find-changed-directories:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files in the docs folder
        id: changed-themes
        uses: tj-actions/changed-files@v35
        with:
          files: *
        # run: |
        #   echo "${{ steps.changed-themes.outputs.all_changed_files }}"

      # - uses: vimtor/action-zip@v1
      #   with:
      #     files: dist/ manifest.json
      #     dest: theme-name.zip
      # - uses: actions/upload-artifact@v1
      # with:
      #   name: theme-name
      #   path: ${{ github.workspace }}/theme-name.zip
