name: Create Theme Zip

on:
  pull_request_target: # When a PR is opened
    types: [opened]
  workflow_dispatch:
jobs:
  find-changed-directories:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get list of changed files
        id: git-diff
        run: |
          CHANGED_DIRS=($(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs -n 1 dirname | awk '!a[$0]++' | awk '!/^(\.)/{print}'))
          echo "${CHANGED_DIRS[@]}"

      # - uses: vimtor/action-zip@v1
      #   with:
      #     files: dist/ manifest.json
      #     dest: theme-name.zip
      # - uses: actions/upload-artifact@v1
      # with:
      #   name: theme-name
      #   path: ${{ github.workspace }}/theme-name.zip
