name: Create Theme Zip

on:
  pull_request_target: # When a PR is opened
    types: [opened]
  workflow_dispatch:
jobs:
  find-changed-directories:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get list of changed files
        id: git-diff
        run: |
          CHANGED_DIRS=($(git diff --name-only HEAD origin/main | awk -F/ '{print $1}' | uniq))
          echo "::set-output name=changed_dirs::${CHANGED_DIRS[@]}"
      - name: Print list of changed directories
        run: |
          echo "Changed directories: ${{ steps.git-diff.outputs.changed_dirs }}"

      # - uses: vimtor/action-zip@v1
      #   with:
      #     files: dist/ manifest.json
      #     dest: theme-name.zip
      # - uses: actions/upload-artifact@v1
      # with:
      #   name: theme-name
      #   path: ${{ github.workspace }}/theme-name.zip
